sudo: required

services:
  - docker

language: python
python: "3.6"

install:
  - pip install ansible molecule[docker] docker

script:
  - molecule test --scenario-name default

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
