sudo: required

services:
  - docker

language: python
python: "2.7"

install:
  - pip install molecule docker

script:
  - molecule test --scenario-name default

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
